### ISSUE TITLE
Fails on Windows due to WSL extension list

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/vscode-styled-jsx-languageserver#2]
Thanks to this comment: https://github.com/Southclaws/vscode-styled-jsx-languageserver/commit/bd364dc0b331fe8f55bb10325ccd75eab50f1b00#r41599206

> Unfortunately your work only fixes things on Mac. On PC, running VS Code with WSL Ubuntu, these errors are thrown on startup and every code-completion keypress:
>
> ```
> [Error - 10:54:09 AM] Request textDocument/documentSymbol failed.
>   Message: Request textDocument/documentSymbol failed with message: Debug Failure. Did not expect SourceFile to have an Identifier in its trivia
>   Code: -32603 
> [Error - 10:54:09 AM] Request textDocument/codeAction failed.
>   Message: Request textDocument/codeAction failed with message: Debug Failure. Did not expect SourceFile to have an Identifier in its trivia
>   Code: -32603 
> [Error - 10:54:09 AM] Request textDocument/colorPresentation failed.
>   Message: Request textDocument/documentColor failed with message: Debug Failure. Did not expect SourceFile to have an Identifier in its trivia
>   Code: -32603 
> [Error - 10:54:09 AM] Request textDocument/colorPresentation failed.
>   Message: Request textDocument/documentColor failed with message: Debug Failure. Did not expect SourceFile to have an Identifier in its trivia
>   Code: -32603 
> [Error - 10:54:10 AM] (node:1828) UnhandledPromiseRejectionWarning: Error: Debug Failure. Did not expect SourceFile to have an Identifier in its trivia
>     at addSyntheticNodes (/home/mg/.vscode-server/extensions/southclaws.vscode-styled-jsx-languageserver-1.1.2/node_modules/typescript/lib/typescript.js:134835:30)
>     at createChildren (/home/mg/.vscode-server/extensions/southclaws.vscode-styled-jsx-languageserver-1.1.2/node_modules/typescript/lib/typescript.js:134824:9)
>     at SourceFileObject.NodeObject.getChildren (/home/mg/.vscode-server/extensions/southclaws.vscode-styled-jsx-languageserver-1.1.2/node_modules/typescript/lib/typescript.js:134768:56)
>     at walk (/home/mg/.vscode-server/extensions/southclaws.vscode-styled-jsx-languageserver-1.1.2/server/out/styled-jsx-utils.js:47:14)
>     at findStyledJsxTaggedTemplate (/home/mg/.vscode-server/extensions/southclaws.vscode-styled-jsx-languageserver-1.1.2/server/out/styled-jsx-utils.js:73:5)
>     at Object.getStyledJsx (/home/mg/.vscode-server/extensions/southclaws.vscode-styled-jsx-languageserver-1.1.2/server/out/styled-jsx-utils.js:127:40)
>     at /home/mg/.vscode-server/extensions/southclaws.vscode-styled-jsx-languageserver-1.1.2/server/out/styled-jsx-server-main.js:128:44
> [Error - 10:54:10 AM] (node:1828) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> [Error - 10:54:10 AM] (node:1828) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> [Error - 10:54:10 AM] Request textDocument/codeAction failed.
>   Message: Request textDocument/codeAction failed with message: Debug Failure. Did not expect SourceFile to have an Identifier in its trivia
>   Code: -32603 
> [Error - 10:54:10 AM] Request textDocument/hover failed.
>   Message: Request textDocument/hover failed with message: Debug Failure. Did not expect SourceFile to have an Identifier in its trivia
>   Code: -32603 
> [Error - 10:54:12 AM] Request textDocument/documentSymbol failed.
>   Message: Request textDocument/documentSymbol failed with message: Debug Failure. Did not expect SourceFile to have an Identifier in its trivia
>   Code: -32603 
> [Error - 10:54:13 AM] Request textDocument/documentSymbol failed.
>   Message: Request textDocument/documentSymbol failed with message: Debug Failure. Did not expect SourceFile to have an Identifier in its trivia
>   Code: -32603 
> [Error - 10:54:13 AM] Request textDocument/colorPresentation failed.
>   Message: Request textDocument/documentColor failed with message: Debug Failure. Did not expect SourceFile to have an Identifier in its trivia
>   Code: -32603 
> ```
>
> On Windows extensions can be installed "locally" (native Windows) or "for WSL Ubuntu" which show up in a separate list. One thing I noticed is that the sister extension, vscode-styled-jsx, which is marked as unmaintained, does not install for WSL Ubuntu, which might be one reason there are so many errors in that environment. However, I get the same errors above when I disable that extension.

**Comment by theoludwig** [comment]
Yes, I'm running the extension with Ubuntu and the extension is not working at all (I have pretty much the same output).

**Comment by Southclaws** [comment]
I'm working on trying to fix it, but I can't reproduce the bug in the debugger somehow.

**Comment by theoludwig** [comment]
Alright good luck @Southclaws!
Also there is a problem for detecting, if it's a style jsx tag or not, the `isStyledJsxTag` function in the `/server/out/styled-jsx-utils.ts` file. For example :

Valid style jsx tag :
```tsx
<style jsx>{`
  p {
    color: red;
  }
`}</style>
```
Unvalid :
```tsx
<style jsx>
  {`
    p {
      color: red;
    }
  `}
</style>
```
It's not valid but it should be, because the code is checking if there is a `{` before the opening of the template string in the first character but the `{` could be anywhere in the tag, hopefully I am understandable.

My quick fix for this (not pretty), is to simply return true with that condition : 
```ts
if (firstAttributeName === 'jsx' || (firstAttributeName === 'global' && secondAttributeName === 'jsx')) {
  return true;
}
```
No need to check if there is a `{` or not, but it could be improved. If you want I can do a pull request, when you fixed the main issue.

**Comment by theoludwig** [comment]
Any news since then @Southclaws ?

**Comment by Southclaws** [comment]
I've been super busy recently so haven't had time to look at this.
