### ISSUE TITLE
Request textDocument/codeAction failed spam in output

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/vscode-styled-jsx-languageserver#2]
```
[Error - 12:36:05] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Debug Failure. Did not expect SourceFile to have an Identifier in its trivia
  Code: -32603 
```

**Comment by Southclaws** [comment]
Maybe related?

```
[Error - 12:38:04] (node:10904) UnhandledPromiseRejectionWarning: Error: Debug Failure. Did not expect SourceFile to have an Identifier in its trivia
    at addSyntheticNodes (c:\Users\Southclaws\.vscode\extensions\southclaws.vscode-styled-jsx-languageserver-1.1.2\node_modules\typescript\lib\typescript.js:134835:30)
    at createChildren (c:\Users\Southclaws\.vscode\extensions\southclaws.vscode-styled-jsx-languageserver-1.1.2\node_modules\typescript\lib\typescript.js:134824:9)
    at SourceFileObject.NodeObject.getChildren (c:\Users\Southclaws\.vscode\extensions\southclaws.vscode-styled-jsx-languageserver-1.1.2\node_modules\typescript\lib\typescript.js:134768:56)
    at walk (c:\Users\Southclaws\.vscode\extensions\southclaws.vscode-styled-jsx-languageserver-1.1.2\server\out\styled-jsx-utils.js:47:14)
    at findStyledJsxTaggedTemplate (c:\Users\Southclaws\.vscode\extensions\southclaws.vscode-styled-jsx-languageserver-1.1.2\server\out\styled-jsx-utils.js:73:5)
    at Object.getStyledJsx (c:\Users\Southclaws\.vscode\extensions\southclaws.vscode-styled-jsx-languageserver-1.1.2\server\out\styled-jsx-utils.js:127:40)
    at c:\Users\Southclaws\.vscode\extensions\southclaws.vscode-styled-jsx-languageserver-1.1.2\server\out\styled-jsx-server-main.js:128:44
[Error - 12:38:04] (node:10904) UnhandledPromiseRejectionWarning: Error: Debug Failure. Did not expect SourceFile to have an Identifier in its trivia
    at addSyntheticNodes (c:\Users\Southclaws\.vscode\extensions\southclaws.vscode-styled-jsx-languageserver-1.1.2\node_modules\typescript\lib\typescript.js:134835:30)
    at createChildren (c:\Users\Southclaws\.vscode\extensions\southclaws.vscode-styled-jsx-languageserver-1.1.2\node_modules\typescript\lib\typescript.js:134824:9)
    at SourceFileObject.NodeObject.getChildren (c:\Users\Southclaws\.vscode\extensions\southclaws.vscode-styled-jsx-languageserver-1.1.2\node_modules\typescript\lib\typescript.js:134768:56)
    at walk (c:\Users\Southclaws\.vscode\extensions\southclaws.vscode-styled-jsx-languageserver-1.1.2\server\out\styled-jsx-utils.js:47:14)
    at findStyledJsxTaggedTemplate (c:\Users\Southclaws\.vscode\extensions\southclaws.vscode-styled-jsx-languageserver-1.1.2\server\out\styled-jsx-utils.js:73:5)
    at Object.getStyledJsx (c:\Users\Southclaws\.vscode\extensions\southclaws.vscode-styled-jsx-languageserver-1.1.2\server\out\styled-jsx-utils.js:127:40)
    at c:\Users\Southclaws\.vscode\extensions\southclaws.vscode-styled-jsx-languageserver-1.1.2\server\out\styled-jsx-server-main.js:128:44
[Error - 12:38:04] (node:10904) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 35)
[Error - 12:38:04] (node:10904) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 35)
```

Seems to happen when opening a TypeScript+JSX (TSX) file.

**Comment by ImFeelingDucky** [comment]
Also getting this issue, with a .jsx file open.

More output:
```
[Error - 11:29:50] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Debug Failure. Did not expect SourceFile to have an Identifier in its trivia
  Code: -32603 
[Error - 11:29:50] (node:30545) UnhandledPromiseRejectionWarning: Error: Debug Failure. Did not expect SourceFile to have an Identifier in its trivia
    at addSyntheticNodes (/home/max/.vscode/extensions/southclaws.vscode-styled-jsx-languageserver-1.1.2/node_modules/typescript/lib/typescript.js:134835:30)
    at createChildren (/home/max/.vscode/extensions/southclaws.vscode-styled-jsx-languageserver-1.1.2/node_modules/typescript/lib/typescript.js:134824:9)
    at SourceFileObject.NodeObject.getChildren (/home/max/.vscode/extensions/southclaws.vscode-styled-jsx-languageserver-1.1.2/node_modules/typescript/lib/typescript.js:134768:56)
    at walk (/home/max/.vscode/extensions/southclaws.vscode-styled-jsx-languageserver-1.1.2/server/out/styled-jsx-utils.js:47:14)
    at findStyledJsxTaggedTemplate (/home/max/.vscode/extensions/southclaws.vscode-styled-jsx-languageserver-1.1.2/server/out/styled-jsx-utils.js:73:5)
    at Object.getStyledJsx (/home/max/.vscode/extensions/southclaws.vscode-styled-jsx-languageserver-1.1.2/server/out/styled-jsx-utils.js:127:40)
    at /home/max/.vscode/extensions/southclaws.vscode-styled-jsx-languageserver-1.1.2/server/out/styled-jsx-server-main.js:128:44
[Error - 11:29:50] (node:30545) UnhandledPromiseRejectionWarning: Error: Debug Failure. Did not expect SourceFile to have an Identifier in its trivia
    at addSyntheticNodes (/home/max/.vscode/extensions/southclaws.vscode-styled-jsx-languageserver-1.1.2/node_modules/typescript/lib/typescript.js:134835:30)
    at createChildren (/home/max/.vscode/extensions/southclaws.vscode-styled-jsx-languageserver-1.1.2/node_modules/typescript/lib/typescript.js:134824:9)
    at SourceFileObject.NodeObject.getChildren (/home/max/.vscode/extensions/southclaws.vscode-styled-jsx-languageserver-1.1.2/node_modules/typescript/lib/typescript.js:134768:56)
    at walk (/home/max/.vscode/extensions/southclaws.vscode-styled-jsx-languageserver-1.1.2/server/out/styled-jsx-utils.js:47:14)
    at findStyledJsxTaggedTemplate (/home/max/.vscode/extensions/southclaws.vscode-styled-jsx-languageserver-1.1.2/server/out/styled-jsx-utils.js:73:5)
    at Object.getStyledJsx (/home/max/.vscode/extensions/southclaws.vscode-styled-jsx-languageserver-1.1.2/server/out/styled-jsx-utils.js:127:40)
    at /home/max/.vscode/extensions/southclaws.vscode-styled-jsx-languageserver-1.1.2/server/out/styled-jsx-server-main.js:128:44
[Error - 11:29:50] (node:30545) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
[Error - 11:29:50] (node:30545) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
[Error - 11:29:50] Request textDocument/colorPresentation failed.
  Message: Request textDocument/documentColor failed with message: Debug Failure. Did not expect SourceFile to have an Identifier in its trivia
  Code: -32603 
```

**Comment by Southclaws** [comment]
Yeah this one is really annoying too because it constantly focuses the "Output" panel while navigating a document.

I'll try and get to know the codebase better and fix this one first, thanks for the logs 👍
